GestorTienda/GestorTienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tiendas.urls'))
]

GestorTienda/tiendas/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views

app_name = 'tiendas'

urlpatterns = [
    path('', lambda request: redirect('/gestionTienda', permanent=False)),
    path('gestionTienda', views.gestionTienda, name='gestionTienda'), #ver las tiendas por defecto
    #path('verTienda/<str:idTienda>', views.verTienda, name='verTienda'),
    path('eliminarTienda/<str:idTienda>', views.eliminarTienda, name='eliminarTienda'),
    path('asignarTienda', views.asignarTienda, name='asignarTienda'),
    
    path('Productos', views.productos, name='productos'),
    path('eliminarProducto/<str:idProducto>', views.eliminarProducto, name='eliminarProducto'),
    path('asignarProducto', views.asignarProducto, name='asignarProducto'),

    path('verTienda/<str:idTienda>/', views.verTienda, name='verTienda'),
    path('eliminarProductoTienda/<str:idProducto>', views.eliminarProductoTienda, name='eliminarProductoTienda'),   
]

GestorTienda/tiendas/models.py
from django.db import models
import datetime

thisTime = datetime.datetime.now() #thisTime.date()

# Create your models here.
class tiendaInfo(models.Model):
    direccion = models.CharField(max_length=32, blank=True, null=True)
    provincia = models.CharField(max_length=32, blank=True, null=True)
    region = models.CharField(max_length=32, blank=True, null=True)
    fechaCreacion = models.CharField(max_length=32, blank=True, null=True)
    telefonoContacto = models.CharField(max_length=32, blank=True, null=True)

    def __str__(self):
        return self.direccion

class productoInfo(models.Model):
    descripcion = models.CharField(max_length=32, blank=True, null=True)
    codigo = models.CharField(max_length=32, blank=True, null=True)
    precioVenta = models.CharField(max_length=32, blank=True, null=True)
    cantidad = models.CharField(max_length=32, blank=True, null=True)
    tiendaRelacionada = models.ForeignKey(tiendaInfo, max_length=32, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.descripcion

GestorTienda/tiendas/views.py
from django.shortcuts import render, get_object_or_404
from django.core.cache import cache
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import tiendaInfo, productoInfo

# TIENDAS

def gestionTienda(request):

    if request.method == 'POST':
        direccion = request.POST.get('direccionTienda')
        provincia = request.POST.get('provinciaTienda')
        region = request.POST.get('regionTienda')
        telefonoContacto = request.POST.get('telefonoTienda')
        tiendaInfo.objects.create(
            direccion=direccion,
            provincia=provincia,
            region=region,
            telefonoContacto=telefonoContacto
        )
        return HttpResponseRedirect(reverse('tiendas:gestionTienda'))

    return render(request, 'gestionTienda.html', {
        'tiendasTot': tiendaInfo.objects.all().order_by('id'),
        'productosTot': productoInfo.objects.all().order_by('id'),
    })

def eliminarTienda(request, idTienda):
    tiendaEliminar = tiendaInfo.objects.get(id=idTienda)
    tiendaEliminar.delete()
    return HttpResponseRedirect(reverse('tiendas:gestionTienda'))

def asignarTienda(request):
    if request.method == 'POST':
        idProducto = request.POST.get('productoSeleccionado')
        idTienda = request.POST.get('tiendaSeleccionada')

        objProducto = productoInfo.objects.get(id=idProducto)
        objTienda = tiendaInfo.objects.get(id=idTienda)     
        
        objTienda.productoinfo_set.add(objProducto)
        
    return HttpResponseRedirect(reverse('tiendas:gestionTienda'))


### PRODUCTOS

def productos(request):

    if request.method == 'POST':
        descripcion = request.POST.get('descripcionProducto')
        codigo = request.POST.get('codigoProducto')
        precioVenta = request.POST.get('precioProducto')
        cantidad = request.POST.get('cantidadProducto')
        productoInfo.objects.create(
            descripcion=descripcion,
            codigo=codigo,
            precioVenta=precioVenta,
            cantidad=cantidad
        )
        return HttpResponseRedirect(reverse('tiendas:productos'))

    return render(request, 'Productos.html', {
        'tiendasTot': tiendaInfo.objects.all().order_by('id'),
        'productosTot': productoInfo.objects.all().order_by('id'),
    })

def eliminarProducto(request, idProducto):
    productoEliminar = productoInfo.objects.get(id=idProducto)
    productoEliminar.delete()
    return HttpResponseRedirect(reverse('tiendas:productos'))

def asignarProducto(request):
    if request.method == 'POST':
        idProducto = request.POST.get('productoSeleccionado')
        idTienda = request.POST.get('tiendaSeleccionada')

        objProducto = productoInfo.objects.get(id=idProducto)
        objTienda = tiendaInfo.objects.get(id=idTienda)

        objProducto.tiendaRelacionada = objTienda
        objProducto.save()

    return HttpResponseRedirect(reverse('tiendas:productos'))



### VER TIENDA
def verTienda(request, idTienda):
    cache.set('idTienda',idTienda)
    
    tiendaSeleccionada = tiendaInfo.objects.get(id=idTienda)
    productosTienda = tiendaSeleccionada.productoinfo_set.all().order_by('id')

    context = {
        'tiendaSeleccionada': tiendaSeleccionada,
        'productosTot': productosTienda
    }
    return render(request, 'verTienda.html', context)

def eliminarProductoTienda(request, idProducto):
    
    idTienda = cache.get('idTienda')
    productoSeleccionado = productoInfo.objects.get(id=idProducto)
    tiendaSeleccionada = tiendaInfo.objects.get(id=idTienda)
    
    tiendaSeleccionada.productoinfo_set.remove(productoSeleccionado)
    

    return verTienda(request, idTienda)
 

GestorTienda/tiendas/templates/FeliminarTienda.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Gestor</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /> <!--- https://fontawesome.com/start -->
    </head>
    <body>
        <div class="bg-primary">
            <div class="container">
                <div class="row">
                    <div class="col-3 text-white">
                        <div class="row">
                            <div class="col-3" >
                                <a class="btn btn-warning" href="{% url 'tiendas:gestionTienda' %}"><i class="fa-solid fa-shop"></i></a>
                            </div>
                            <div class="col-3">
                                <a class="btn btn-warning" href="{% url 'tiendas:productos' %}"><i class="fa-solid fa-tags"></i></a>
                            </div>
                            <div class="col-3">
                                <h5>Vista de tienda</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 text-center">
            <h4> {{ productoSeleccionado.descripcion }} idProd: {{ idProducto }} </h4>
            <h4> {{ tiendaSeleccionada.direccion }} idTienda: {{ idTienda }} </h4>
        </div>
        <br>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered">
                        <thead>
                            <th>direccion</th>
                            <th> </th>
                            <th> </th>
                            <th> </th>
                            <th>Eliminar Producto</th>
                        </thead>
                        <tbody>
                            {% for producto in productosTot %}
                            <tr>
                                <td>{{ producto.direccion }}</td>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td class="text-center"><a class="btn btn-danger" href=""><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

GestorTienda/tiendas/templates/Productos.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Gestor</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /> <!--- https://fontawesome.com/start -->
    </head>
    <body>
        <div class="bg-primary">
            <div class="container">
                <div class="row">
                    <div class="col-3 text-white">
                        <div class="row">
                            <div class="col-3" >
                                <a class="btn btn-warning" href="{% url 'tiendas:gestionTienda' %}"><i class="fa-solid fa-shop"></i></a>
                            </div>
                            <div class="col-3">
                                <a class="btn btn-success" href=""><i class="fa-solid fa-tags"></i></a>
                            </div>
                            <div class="col-3">
                                <h5>Productos</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 text-center">
            <h1>Gestión de productos</h1>
        </div>
        <div class="container mt-5">
            <div class="row justify-content-between">
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevoProducto">Producto <i class="fa-solid fa-plus"></i></button>
                </div>
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#asignarProducto">Asignar <i class="fa-solid fa-store"></i></button>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered">
                        <thead>
                            <th>Descripción</th>
                            <th>Código</th>
                            <th>Precio de Venta</th>
                            <th>Cantidad</th>
                            <th>Eliminar Producto</th>
                        </thead>
                        <tbody>
                            {% for producto in productosTot %}
                            <tr>
                                <td>{{ producto.descripcion }}</td>
                                <td>{{ producto.codigo }}</td>
                                <td>{{ producto.precioVenta }}</td>
                                <td>{{ producto.cantidad }}</td>
                                <td class="text-center"><a class="btn btn-danger" href="{% url 'tiendas:eliminarProducto' producto.id %}"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </body>
</html>


<div class="modal fade" tabindex="-1" id="nuevoProducto" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{% url 'tiendas:productos' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Nuevo Producto</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-center mb-3">
                        <div class="col-5">
                            <label>Descripción</label>
                            <input class="form-control" type="text" name="descripcionProducto" required>
                        </div>
                        <div class="col-5">
                            <label>Código</label>
                            <input class="form-control" type="text" name="codigoProducto" required>
                        </div>
                        <div class="col-5">
                            <label>Precio de Venta</label>
                            <input class="form-control" type="number" min="0" step="0.01" name="precioProducto" required>
                        </div>
                        <div class="col-5">
                            <label>Cantidad</label>
                            <input class="form-control" type="number" min="0" name="cantidadProducto" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Crear Producto</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" id="asignarProducto" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{% url 'tiendas:asignarProducto' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Asignar producto a tienda</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-center mb-3">
                        <div class="col-5">
                            <label>Tienda</label>
                            <select class="form-select" name="tiendaSeleccionada" required>
                                <option value="" selected></option>
                                {% for tienda in tiendasTot %}
                                <option value="{{ tienda.id }}">{{ tienda.direccion }} {{ tienda.provincia}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-5">
                            <label>Producto</label>
                            <select class="form-select" name="productoSeleccionado" required>
                                <option value="" selected></option>
                                {% for producto in productosTot %}
                                <option value="{{ producto.id }}">{{ producto.descripcion }} {{ producto.codigo }}</option>
                                {% endfor %}
                            </select>
                        </div>                        
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Asignar</button>
                </div>
            </form>
        </div>
    </div>
</div>

GestorTienda/tiendas/templates/gestionTienda.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Gestor</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="bg-primary">
            <div class="container">
                <div class="row">
                    <div class="col-3 text-white">
                        <div class="row">
                            <div class="col-3" >
                                <a class="btn btn-success" href=""><i class="fa-solid fa-shop"></i></a>
                            </div>
                            <div class="col-3">
                                <a class="btn btn-warning" href="{% url 'tiendas:productos' %}"><i class="fa-solid fa-tags"></i></a>
                            </div>
                            <div class="col-3">
                                <h5>Tiendas</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 text-center">
            <h1>Gestión de tiendas</h1>
        </div>
        <div class="container mt-5">
            <div class="row justify-content-between">
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevaTienda">Tienda <i class="fa-solid fa-plus"></i></button>
                </div>
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#asignarTienda">Asignar <i class="fa-solid fa-boxes-stacked"></i></button>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered">
                        <thead>
                            <th>Dirección</th>
                            <th>Provincia</th>
                            <th>Región</th>
                            <th>Fecha de creación</th>
                            <th>Teléfono Contacto</th>
                            <th>Ver productos</th>
                            <th>Eliminar tienda</th>
                        </thead>
                        <tbody>
                            {% for tienda in tiendasTot %}
                            <tr>
                                <td>{{ tienda.direccion }}</td>
                                <td>{{ tienda.provincia }}</td>
                                <td>{{ tienda.region }}</td>
                                <td>{{ tienda.fechaCreacion }}</td>
                                <td>{{ tienda.telefonoContacto }}</td>
                                <td class="text-center"><a class="btn btn-info" href="{% url 'tiendas:verTienda' tienda.id %}"><i class="fa-solid fa-eye"></i></a></td>
                                <td class="text-center"><a class="btn btn-danger" href="{% url 'tiendas:eliminarTienda' tienda.id %}"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </body>
</html>


<div class="modal fade" tabindex="-1" id="nuevaTienda" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{% url 'tiendas:gestionTienda' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Nueva Tienda</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-center mb-3">
                        <div class="col-5">
                            <label>Dirección</label>
                            <input class="form-control" type="text" name="direccionTienda" required>
                        </div>
                        <div class="col-5">
                            <label>Provincia</label>
                            <input class="form-control" type="text" name="provinciaTienda" required>
                        </div>
                        <div class="col-5">
                            <label>Región</label>
                            <input class="form-control" type="text" name="regionTienda" required>
                        </div>
                        <div class="col-5">
                            <label>Teléfono Contacto</label>
                            <input class="form-control" type="text" name="telefonoTienda" required>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Crear tienda</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" id="asignarTienda" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{% url 'tiendas:asignarTienda' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Asignar producto a tienda</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-center mb-3">
                        <div class="col-5">
                            <label>Tienda</label>
                            <select class="form-select" name="tiendaSeleccionada" required>
                                <option value="" selected></option>
                                {% for tienda in tiendasTot %}
                                <option value="{{ tienda.id }}">{{ tienda.direccion }} {{ tienda.provincia}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-5">
                            <label>Producto</label>
                            <select class="form-select" name="productoSeleccionado" required>
                                <option value="" selected></option>
                                {% for producto in productosTot %}
                                <option value="{{ producto.id }}">{{ producto.descripcion }} {{ producto.codigo }}</option>
                                {% endfor %}
                            </select>
                        </div>                        
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn btn-primary">Asignar</button>
                </div>
            </form>
        </div>
    </div>
</div>

GestorTienda/tiendas/templates/verTienda.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Gestor</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /> <!--- https://fontawesome.com/start -->
    </head>
    <body>
        <div class="bg-primary">
            <div class="container">
                <div class="row">
                    <div class="col-3 text-white">
                        <div class="row">
                            <div class="col-3" >
                                <a class="btn btn-warning" href="{% url 'tiendas:gestionTienda' %}"><i class="fa-solid fa-shop"></i></a>
                            </div>
                            <div class="col-3">
                                <a class="btn btn-warning" href="{% url 'tiendas:productos' %}"><i class="fa-solid fa-tags"></i></a>
                            </div>
                            <div class="col-3">
                                <h5>Vista de tienda</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="mt-5 text-center">
            <h2>Productos tienda {{ tiendaSeleccionada.direccion }}, {{ tiendaSeleccionada.provincia }}, {{ tiendaSeleccionada.region }}</h2>
        </div>
        <br>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered">
                        <thead>
                            <th>Descripción</th>
                            <th>Código</th>
                            <th>Precio de Venta</th>
                            <th>Cantidad</th>
                            <th>Eliminar Producto</th>
                        </thead>
                        <tbody>
                            {% for producto in productosTot %}
                            <tr>
                                <td>{{ producto.descripcion }}</td>
                                <td>{{ producto.codigo }}</td>
                                <td>{{ producto.precioVenta }}</td>
                                <td>{{ producto.cantidad }}</td>
                                <td class="text-center"><a class="btn btn-danger" href="{% url 'tiendas:eliminarProductoTienda' producto.id %}"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>